# Generated by Django 6.0.1 on 2026-01-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
